# Generated by Django 4.2.13 on 2024-06-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('logged_in', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=256)),
                ('is_success', models.BooleanField(default=None)),
            ],
            options={
                'ordering': ['-logged_in'],
            },
        ),
    ]
