# Generated by Django 4.2.13 on 2024-06-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_accountrecovery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrecovery',
            name='is_forget',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountrecovery',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
